spring:
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb:27017/docker-goals?authSource=admin
logging:
  level:
    root:
      INFO
  file:
    path: ./docker-demo-backend/logs
server:
  port: 8080