spring:
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.gggje.mongodb.net/Goal?retryWrites=true&w=majority&appName=Cluster0
      database: Goal
      ssl:
        enabled: true