apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
spec:
  volumeName: logs-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi